name = "trabalho_escape"
version = "1.0.0"

# O alvo padrão é Erlang (para rodar no terminal com gleam run)
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0"
gleam_erlang = ">= 0.25.0"
simplifile = ">= 2.0.0"